-- Create IMPORT_LOGS table for tracking PDF imports
CREATE TABLE IF NOT EXISTS IMPORT_LOGS (
    ID VARCHAR(36) PRIMARY KEY,
    ACADEMIC_YEAR VARCHAR(10) NOT NULL,
    SEMESTER VARCHAR(20) NOT NULL,
    IMPORT_DATE DATETIME NOT NULL,
    SUMMARY TEXT,
    STATUS VARCHAR(20) DEFAULT 'completed',
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Create index for faster queries
CREATE INDEX idx_import_logs_date ON IMPORT_LOGS(IMPORT_DATE);
CREATE INDEX idx_import_logs_academic ON IMPORT_LOGS(ACADEMIC_YEAR, SEMESTER);




