-- Archive Schema - Add ARCHIVED status to existing tables
-- MySQL doesn't support IF NOT EXISTS for ALTER TABLE, so we check first

USE iot_attendance;

-- Add ARCHIVED_AT and ARCHIVED_BY columns to USERS table
SET @col_exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'USERS' AND COLUMN_NAME = 'ARCHIVED_AT');
SET @sql = IF(@col_exists = 0, 
    'ALTER TABLE USERS ADD COLUMN ARCHIVED_AT TIMESTAMP NULL DEFAULT NULL', 
    'SELECT "Column ARCHIVED_AT already exists in USERS"');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @col_exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'USERS' AND COLUMN_NAME = 'ARCHIVED_BY');
SET @sql = IF(@col_exists = 0, 
    'ALTER TABLE USERS ADD COLUMN ARCHIVED_BY CHAR(36) NULL DEFAULT NULL', 
    'SELECT "Column ARCHIVED_BY already exists in USERS"');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @col_exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'USERS' AND COLUMN_NAME = 'ARCHIVE_REASON');
SET @sql = IF(@col_exists = 0, 
    'ALTER TABLE USERS ADD COLUMN ARCHIVE_REASON TEXT NULL DEFAULT NULL', 
    'SELECT "Column ARCHIVE_REASON already exists in USERS"');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

-- Add columns to SUBJECTS table
SET @col_exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'SUBJECTS' AND COLUMN_NAME = 'ARCHIVED_AT');
SET @sql = IF(@col_exists = 0, 
    'ALTER TABLE SUBJECTS ADD COLUMN ARCHIVED_AT TIMESTAMP NULL DEFAULT NULL', 
    'SELECT "Column ARCHIVED_AT already exists in SUBJECTS"');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @col_exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'SUBJECTS' AND COLUMN_NAME = 'ARCHIVED_BY');
SET @sql = IF(@col_exists = 0, 
    'ALTER TABLE SUBJECTS ADD COLUMN ARCHIVED_BY CHAR(36) NULL DEFAULT NULL', 
    'SELECT "Column ARCHIVED_BY already exists in SUBJECTS"');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @col_exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'SUBJECTS' AND COLUMN_NAME = 'ARCHIVE_REASON');
SET @sql = IF(@col_exists = 0, 
    'ALTER TABLE SUBJECTS ADD COLUMN ARCHIVE_REASON TEXT NULL DEFAULT NULL', 
    'SELECT "Column ARCHIVE_REASON already exists in SUBJECTS"');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

-- Add columns to ROOMS table
SET @col_exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'ROOMS' AND COLUMN_NAME = 'ARCHIVED_AT');
SET @sql = IF(@col_exists = 0, 
    'ALTER TABLE ROOMS ADD COLUMN ARCHIVED_AT TIMESTAMP NULL DEFAULT NULL', 
    'SELECT "Column ARCHIVED_AT already exists in ROOMS"');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @col_exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'ROOMS' AND COLUMN_NAME = 'ARCHIVED_BY');
SET @sql = IF(@col_exists = 0, 
    'ALTER TABLE ROOMS ADD COLUMN ARCHIVED_BY CHAR(36) NULL DEFAULT NULL', 
    'SELECT "Column ARCHIVED_BY already exists in ROOMS"');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @col_exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'ROOMS' AND COLUMN_NAME = 'ARCHIVE_REASON');
SET @sql = IF(@col_exists = 0, 
    'ALTER TABLE ROOMS ADD COLUMN ARCHIVE_REASON TEXT NULL DEFAULT NULL', 
    'SELECT "Column ARCHIVE_REASON already exists in ROOMS"');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

-- Add columns to CLASSSCHEDULES table
SET @col_exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'CLASSSCHEDULES' AND COLUMN_NAME = 'ARCHIVED_AT');
SET @sql = IF(@col_exists = 0, 
    'ALTER TABLE CLASSSCHEDULES ADD COLUMN ARCHIVED_AT TIMESTAMP NULL DEFAULT NULL', 
    'SELECT "Column ARCHIVED_AT already exists in CLASSSCHEDULES"');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @col_exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'CLASSSCHEDULES' AND COLUMN_NAME = 'ARCHIVED_BY');
SET @sql = IF(@col_exists = 0, 
    'ALTER TABLE CLASSSCHEDULES ADD COLUMN ARCHIVED_BY CHAR(36) NULL DEFAULT NULL', 
    'SELECT "Column ARCHIVED_BY already exists in CLASSSCHEDULES"');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @col_exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'CLASSSCHEDULES' AND COLUMN_NAME = 'ARCHIVE_REASON');
SET @sql = IF(@col_exists = 0, 
    'ALTER TABLE CLASSSCHEDULES ADD COLUMN ARCHIVE_REASON TEXT NULL DEFAULT NULL', 
    'SELECT "Column ARCHIVE_REASON already exists in CLASSSCHEDULES"');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

-- Add columns to ATTENDANCERECORDS table
SET @col_exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'ATTENDANCERECORDS' AND COLUMN_NAME = 'ARCHIVED_AT');
SET @sql = IF(@col_exists = 0, 
    'ALTER TABLE ATTENDANCERECORDS ADD COLUMN ARCHIVED_AT TIMESTAMP NULL DEFAULT NULL', 
    'SELECT "Column ARCHIVED_AT already exists in ATTENDANCERECORDS"');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @col_exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'ATTENDANCERECORDS' AND COLUMN_NAME = 'ARCHIVED_BY');
SET @sql = IF(@col_exists = 0, 
    'ALTER TABLE ATTENDANCERECORDS ADD COLUMN ARCHIVED_BY CHAR(36) NULL DEFAULT NULL', 
    'SELECT "Column ARCHIVED_BY already exists in ATTENDANCERECORDS"');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @col_exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'ATTENDANCERECORDS' AND COLUMN_NAME = 'ARCHIVE_REASON');
SET @sql = IF(@col_exists = 0, 
    'ALTER TABLE ATTENDANCERECORDS ADD COLUMN ARCHIVE_REASON TEXT NULL DEFAULT NULL', 
    'SELECT "Column ARCHIVE_REASON already exists in ATTENDANCERECORDS"');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

-- Add columns to SESSIONS table
SET @col_exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'SESSIONS' AND COLUMN_NAME = 'ARCHIVED_AT');
SET @sql = IF(@col_exists = 0, 
    'ALTER TABLE SESSIONS ADD COLUMN ARCHIVED_AT TIMESTAMP NULL DEFAULT NULL', 
    'SELECT "Column ARCHIVED_AT already exists in SESSIONS"');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @col_exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'SESSIONS' AND COLUMN_NAME = 'ARCHIVED_BY');
SET @sql = IF(@col_exists = 0, 
    'ALTER TABLE SESSIONS ADD COLUMN ARCHIVED_BY CHAR(36) NULL DEFAULT NULL', 
    'SELECT "Column ARCHIVED_BY already exists in SESSIONS"');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @col_exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'SESSIONS' AND COLUMN_NAME = 'ARCHIVE_REASON');
SET @sql = IF(@col_exists = 0, 
    'ALTER TABLE SESSIONS ADD COLUMN ARCHIVE_REASON TEXT NULL DEFAULT NULL', 
    'SELECT "Column ARCHIVE_REASON already exists in SESSIONS"');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

-- Add columns to SUBJECTENROLLMENT table
SET @col_exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'SUBJECTENROLLMENT' AND COLUMN_NAME = 'ARCHIVED_AT');
SET @sql = IF(@col_exists = 0, 
    'ALTER TABLE SUBJECTENROLLMENT ADD COLUMN ARCHIVED_AT TIMESTAMP NULL DEFAULT NULL', 
    'SELECT "Column ARCHIVED_AT already exists in SUBJECTENROLLMENT"');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @col_exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'SUBJECTENROLLMENT' AND COLUMN_NAME = 'ARCHIVED_BY');
SET @sql = IF(@col_exists = 0, 
    'ALTER TABLE SUBJECTENROLLMENT ADD COLUMN ARCHIVED_BY CHAR(36) NULL DEFAULT NULL', 
    'SELECT "Column ARCHIVED_BY already exists in SUBJECTENROLLMENT"');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @col_exists = (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'SUBJECTENROLLMENT' AND COLUMN_NAME = 'ARCHIVE_REASON');
SET @sql = IF(@col_exists = 0, 
    'ALTER TABLE SUBJECTENROLLMENT ADD COLUMN ARCHIVE_REASON TEXT NULL DEFAULT NULL', 
    'SELECT "Column ARCHIVE_REASON already exists in SUBJECTENROLLMENT"');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

-- Create indexes for better performance
CREATE INDEX idx_users_archived ON USERS(ARCHIVED_AT);
CREATE INDEX idx_subjects_archived ON SUBJECTS(ARCHIVED_AT);
CREATE INDEX idx_rooms_archived ON ROOMS(ARCHIVED_AT);
CREATE INDEX idx_schedules_archived ON CLASSSCHEDULES(ARCHIVED_AT);
CREATE INDEX idx_attendance_archived ON ATTENDANCERECORDS(ARCHIVED_AT);
CREATE INDEX idx_sessions_archived ON SESSIONS(ARCHIVED_AT);
CREATE INDEX idx_enrollment_archived ON SUBJECTENROLLMENT(ARCHIVED_AT);
