-- Archive Schema - Simple version without IF NOT EXISTS checks
-- Run this in MySQL Workbench

USE iot_attendance;

-- Add ARCHIVED columns to USERS
ALTER TABLE USERS ADD COLUMN ARCHIVED_AT TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE USERS ADD COLUMN ARCHIVED_BY CHAR(36) NULL DEFAULT NULL;
ALTER TABLE USERS ADD COLUMN ARCHIVE_REASON TEXT NULL DEFAULT NULL;

-- Add ARCHIVED columns to SUBJECTS
ALTER TABLE SUBJECTS ADD COLUMN ARCHIVED_AT TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SUBJECTS ADD COLUMN ARCHIVED_BY CHAR(36) NULL DEFAULT NULL;
ALTER TABLE SUBJECTS ADD COLUMN ARCHIVE_REASON TEXT NULL DEFAULT NULL;

-- Add ARCHIVED columns to ROOMS
ALTER TABLE ROOMS ADD COLUMN ARCHIVED_AT TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE ROOMS ADD COLUMN ARCHIVED_BY CHAR(36) NULL DEFAULT NULL;
ALTER TABLE ROOMS ADD COLUMN ARCHIVE_REASON TEXT NULL DEFAULT NULL;

-- Add ARCHIVED columns to CLASSSCHEDULES
ALTER TABLE CLASSSCHEDULES ADD COLUMN ARCHIVED_AT TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE CLASSSCHEDULES ADD COLUMN ARCHIVED_BY CHAR(36) NULL DEFAULT NULL;
ALTER TABLE CLASSSCHEDULES ADD COLUMN ARCHIVE_REASON TEXT NULL DEFAULT NULL;

-- Add ARCHIVED columns to ATTENDANCERECORDS
ALTER TABLE ATTENDANCERECORDS ADD COLUMN ARCHIVED_AT TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE ATTENDANCERECORDS ADD COLUMN ARCHIVED_BY CHAR(36) NULL DEFAULT NULL;
ALTER TABLE ATTENDANCERECORDS ADD COLUMN ARCHIVE_REASON TEXT NULL DEFAULT NULL;

-- Add ARCHIVED columns to SESSIONS
ALTER TABLE SESSIONS ADD COLUMN ARCHIVED_AT TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SESSIONS ADD COLUMN ARCHIVED_BY CHAR(36) NULL DEFAULT NULL;
ALTER TABLE SESSIONS ADD COLUMN ARCHIVE_REASON TEXT NULL DEFAULT NULL;

-- Add ARCHIVED columns to SUBJECTENROLLMENT
ALTER TABLE SUBJECTENROLLMENT ADD COLUMN ARCHIVED_AT TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE SUBJECTENROLLMENT ADD COLUMN ARCHIVED_BY CHAR(36) NULL DEFAULT NULL;
ALTER TABLE SUBJECTENROLLMENT ADD COLUMN ARCHIVE_REASON TEXT NULL DEFAULT NULL;

-- Create indexes
CREATE INDEX idx_users_archived ON USERS(ARCHIVED_AT);
CREATE INDEX idx_subjects_archived ON SUBJECTS(ARCHIVED_AT);
CREATE INDEX idx_rooms_archived ON ROOMS(ARCHIVED_AT);
CREATE INDEX idx_schedules_archived ON CLASSSCHEDULES(ARCHIVED_AT);
CREATE INDEX idx_attendance_archived ON ATTENDANCERECORDS(ARCHIVED_AT);
CREATE INDEX idx_sessions_archived ON SESSIONS(ARCHIVED_AT);
CREATE INDEX idx_enrollment_archived ON SUBJECTENROLLMENT(ARCHIVED_AT);

