CREATE TABLE IF NOT EXISTS SECURITY_AUDIT_LOGS (
    AUDIT_ID CHAR(36) NOT NULL PRIMARY KEY DEFAULT (UUID()),
    EVENT_TYPE VARCHAR(64) NOT NULL,
    ACTOR_USER_ID CHAR(36) NULL,
    TARGET_USER_ID CHAR(36) NULL,
    METADATA_JSON JSON NULL,
    IP_ADDRESS VARCHAR(45) NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX IDX_SECURITY_AUDIT_EVENT (EVENT_TYPE),
    INDEX IDX_SECURITY_AUDIT_ACTOR (ACTOR_USER_ID),
    INDEX IDX_SECURITY_AUDIT_TARGET (TARGET_USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;



