-- IoT Attendance System Database Schema
-- Liceo de Cagayan University

CREATE DATABASE IF NOT EXISTS iot_attendance;
USE iot_attendance;

-- Users table
CREATE TABLE USERS (
    USERID CHAR(36) PRIMARY KEY,
    FIRSTNAME VARCHAR(50) NOT NULL,
    LASTNAME VARCHAR(50) NOT NULL,
    USERTYPE ENUM('student', 'instructor', 'admin') NOT NULL,
    YEARLEVEL ENUM('1', '2', '3', '4', '5') DEFAULT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    PASSWORD_HASH VARCHAR(255) DEFAULT NULL,
    PHONENUMBER VARCHAR(15) DEFAULT NULL,
    DEPARTMENT VARCHAR(100) DEFAULT NULL,
    STUDENTID VARCHAR(20) UNIQUE DEFAULT NULL,
    FACULTYID VARCHAR(20) UNIQUE DEFAULT NULL,
    EMPLOYEEID VARCHAR(20) UNIQUE DEFAULT NULL,
    RFIDTAG VARCHAR(100) UNIQUE DEFAULT NULL,
    STATUS ENUM('Active', 'Inactive') DEFAULT 'Active',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- AuthenticationMethods table
CREATE TABLE AUTHENTICATIONMETHODS (
    AUTHID CHAR(36) PRIMARY KEY,
    USERID CHAR(36) NOT NULL,
    METHODTYPE ENUM('RFID', 'Fingerprint') NOT NULL,
    IDENTIFIER VARCHAR(100) UNIQUE NOT NULL,
    RFIDTAGNUMBER VARCHAR(100) UNIQUE DEFAULT NULL,
    FINGERPRINTTEMPLATE BLOB DEFAULT NULL,
    ISACTIVE BOOLEAN DEFAULT TRUE,
    DATEREGISTERED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LASTUPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    STATUS ENUM('Active', 'Suspended') DEFAULT 'Active',
    FOREIGN KEY (USERID) REFERENCES USERS(USERID) ON DELETE CASCADE,
    INDEX idx_identifier_method (IDENTIFIER, METHODTYPE)
);

-- Rooms table
CREATE TABLE ROOMS (
    ROOMID CHAR(36) PRIMARY KEY,
    ROOMNUMBER VARCHAR(20) UNIQUE NOT NULL,
    ROOMNAME VARCHAR(100) DEFAULT NULL,
    BUILDING VARCHAR(100) NOT NULL,
    CAPACITY INT UNSIGNED DEFAULT NULL,
    DEVICEID VARCHAR(100) DEFAULT NULL,
    DOORSTATUS ENUM('locked', 'unlocked') DEFAULT 'locked',
    STATUS ENUM('Available', 'Maintenance') DEFAULT 'Available',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Subjects table
CREATE TABLE SUBJECTS (
    SUBJECTID CHAR(36) PRIMARY KEY,
    SUBJECTCODE VARCHAR(20) NOT NULL,
    SUBJECTNAME VARCHAR(255) NOT NULL,
    INSTRUCTORID CHAR(36) NOT NULL,
    SEMESTER VARCHAR(20) NOT NULL,
    YEAR YEAR NOT NULL,
    ACADEMICYEAR VARCHAR(10) NOT NULL,
    DESCRIPTION TEXT DEFAULT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (INSTRUCTORID) REFERENCES USERS(USERID) ON DELETE CASCADE,
    UNIQUE KEY unique_subject_term (SUBJECTCODE, SEMESTER, ACADEMICYEAR)
);

-- ClassSchedules table
CREATE TABLE CLASSSCHEDULES (
    SCHEDULEID CHAR(36) PRIMARY KEY,
    SUBJECTID CHAR(36) NOT NULL,
    ROOMID CHAR(36) NOT NULL,
    DAYOFWEEK ENUM('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday') NOT NULL,
    STARTTIME TIME NOT NULL,
    ENDTIME TIME NOT NULL,
    ACADEMICYEAR VARCHAR(10) NOT NULL,
    SEMESTER VARCHAR(20) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (SUBJECTID) REFERENCES SUBJECTS(SUBJECTID) ON DELETE CASCADE,
    FOREIGN KEY (ROOMID) REFERENCES ROOMS(ROOMID) ON DELETE CASCADE
);

-- SubjectEnrollment table
CREATE TABLE SUBJECTENROLLMENT (
    ENROLLMENTID CHAR(36) PRIMARY KEY,
    USERID CHAR(36) NOT NULL,
    SUBJECTID CHAR(36) NOT NULL,
    ENROLLMENTDATE DATE DEFAULT (CURRENT_DATE),
    ACADEMICYEAR VARCHAR(10) NOT NULL,
    SEMESTER VARCHAR(20) NOT NULL,
    STATUS ENUM('enrolled', 'dropped', 'completed') DEFAULT 'enrolled',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USERID) REFERENCES USERS(USERID) ON DELETE CASCADE,
    FOREIGN KEY (SUBJECTID) REFERENCES SUBJECTS(SUBJECTID) ON DELETE CASCADE,
    UNIQUE KEY unique_enrollment (USERID, SUBJECTID, ACADEMICYEAR, SEMESTER)
);

-- Sessions table (for tracking active class sessions)
CREATE TABLE SESSIONS (
    SESSIONID CHAR(36) PRIMARY KEY,
    SCHEDULEID CHAR(36) NOT NULL,
    INSTRUCTORID CHAR(36) NOT NULL,
    ROOMID CHAR(36) NOT NULL,
    SESSIONDATE DATE NOT NULL,
    STARTTIME TIMESTAMP DEFAULT NULL,
    ENDTIME TIMESTAMP DEFAULT NULL,
    ATTENDANCE_WINDOW_MINUTES INT DEFAULT 15,
    ATTENDANCE_DEADLINE TIMESTAMP DEFAULT NULL,
    STATUS ENUM('waiting', 'active', 'ended', 'cancelled') DEFAULT 'waiting',
    DOORUNLOCKEDAT TIMESTAMP DEFAULT NULL,
    DOORLOCKEDAT TIMESTAMP DEFAULT NULL,
    ACADEMICYEAR VARCHAR(10) NOT NULL,
    SEMESTER VARCHAR(20) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (SCHEDULEID) REFERENCES CLASSSCHEDULES(SCHEDULEID) ON DELETE CASCADE,
    FOREIGN KEY (INSTRUCTORID) REFERENCES USERS(USERID) ON DELETE CASCADE,
    FOREIGN KEY (ROOMID) REFERENCES ROOMS(ROOMID) ON DELETE CASCADE,
    INDEX idx_session_date_status (SESSIONDATE, STATUS),
    INDEX idx_room_date_status (ROOMID, SESSIONDATE, STATUS)
);

-- AttendanceRecords table
CREATE TABLE ATTENDANCERECORDS (
    ATTENDANCEID CHAR(36) PRIMARY KEY,
    USERID CHAR(36) NOT NULL,
    SCHEDULEID CHAR(36) NOT NULL,
    SESSIONID CHAR(36) DEFAULT NULL,
    SCANTYPE ENUM('time_in', 'time_out') NOT NULL,
    SCANDATETIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DATE DATE NOT NULL,
    TIMEIN TIME DEFAULT NULL,
    AUTHMETHOD ENUM('RFID', 'Fingerprint') NOT NULL,
    LOCATION ENUM('inside', 'outside') NOT NULL,
    STATUS ENUM('Present', 'Late', 'Absent') NOT NULL,
    ACADEMICYEAR VARCHAR(10) NOT NULL,
    SEMESTER VARCHAR(20) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (USERID) REFERENCES USERS(USERID) ON DELETE CASCADE,
    FOREIGN KEY (SCHEDULEID) REFERENCES CLASSSCHEDULES(SCHEDULEID) ON DELETE CASCADE,
    FOREIGN KEY (SESSIONID) REFERENCES SESSIONS(SESSIONID) ON DELETE SET NULL,
    INDEX idx_user_date (USERID, DATE),
    INDEX idx_schedule_date (SCHEDULEID, DATE)
);

-- AccessLogs table
CREATE TABLE ACCESSLOGS (
    LOGID CHAR(36) PRIMARY KEY,
    USERID CHAR(36) DEFAULT NULL,
    ROOMID CHAR(36) NOT NULL,
    TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ACCESSTYPE ENUM('session_start', 'session_end', 'attendance_scan', 'door_override') NOT NULL,
    AUTHMETHOD ENUM('RFID', 'Fingerprint', 'Manual') NOT NULL,
    LOCATION ENUM('inside', 'outside') NOT NULL,
    RESULT ENUM('success', 'denied') NOT NULL,
    REASON VARCHAR(255) DEFAULT NULL,
    IPADDRESS VARCHAR(45) DEFAULT NULL,
    USERAGENT TEXT DEFAULT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USERID) REFERENCES USERS(USERID) ON DELETE SET NULL,
    FOREIGN KEY (ROOMID) REFERENCES ROOMS(ROOMID) ON DELETE CASCADE,
    INDEX idx_timestamp (TIMESTAMP),
    INDEX idx_user_timestamp (USERID, TIMESTAMP)
);

-- Devices table
CREATE TABLE DEVICES (
    DEVICEID CHAR(36) PRIMARY KEY,
    DEVICETYPE ENUM('RFID_Reader', 'Fingerprint_Scanner', 'Door_Controller') NOT NULL,
    DEVICENAME VARCHAR(100) NOT NULL,
    LOCATION VARCHAR(255) NOT NULL,
    ROOMID CHAR(36) NOT NULL,
    IPADDRESS VARCHAR(45) DEFAULT NULL,
    MACADDRESS VARCHAR(17) DEFAULT NULL,
    FIRMWAREVERSION VARCHAR(50) DEFAULT NULL,
    LASTMAINTENANCE DATE DEFAULT NULL,
    LASTSEEN TIMESTAMP DEFAULT NULL,
    STATUS ENUM('Active', 'Inactive', 'Maintenance') DEFAULT 'Active',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (ROOMID) REFERENCES ROOMS(ROOMID) ON DELETE CASCADE
);

-- Settings table (for system configuration)
CREATE TABLE SETTINGS (
    SETTINGID CHAR(36) PRIMARY KEY,
    SETTINGKEY VARCHAR(100) UNIQUE NOT NULL,
    SETTINGVALUE TEXT NOT NULL,
    DESCRIPTION TEXT DEFAULT NULL,
    CATEGORY VARCHAR(50) DEFAULT 'general',
    ISEDITABLE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Insert default system settings
INSERT INTO SETTINGS (SETTINGID, SETTINGKEY, SETTINGVALUE, DESCRIPTION, CATEGORY) VALUES
(UUID(), 'current_academic_year', '2024-2025', 'Current academic year', 'academic'),
(UUID(), 'current_semester', 'First Semester', 'Current semester', 'academic'),
(UUID(), 'late_tolerance_minutes', '15', 'Minutes after class start time to mark as late', 'attendance'),
(UUID(), 'system_name', 'IoT Attendance System', 'System display name', 'general'),
(UUID(), 'institution_name', 'Liceo de Cagayan University', 'Institution name', 'general'),
(UUID(), 'door_auto_lock_minutes', '30', 'Minutes to auto-lock door after session ends', 'security'),
(UUID(), 'max_login_attempts', '5', 'Maximum login attempts before account lockout', 'security'),
(UUID(), 'session_timeout_hours', '8', 'Hours before inactive session expires', 'security');

-- Insert default admin user with hashed password (password: admin123)
INSERT INTO USERS (USERID, FIRSTNAME, LASTNAME, EMAIL, PASSWORD_HASH, USERTYPE, DEPARTMENT, EMPLOYEEID) 
VALUES (UUID(), 'System', 'Administrator', 'admin@liceo.edu.ph', '$2a$10$rOvROqn7jYXqEJRE3lfzVeUYJfzqnXj2vHCdB6EjBGNOyN5Qlqj2G', 'admin', 'CIT Department', 'EMP001');

-- Insert sample rooms (WAC Building)
INSERT INTO ROOMS (ROOMID, ROOMNUMBER, ROOMNAME, BUILDING, CAPACITY, DOORSTATUS) VALUES
(UUID(), 'LAB-01', 'Lab 1', 'WAC Building', 40, 'locked'),
(UUID(), 'LAB-02', 'Lab 2', 'WAC Building', 35, 'locked'),
(UUID(), 'CISCO-LAB', 'Cisco Lab', 'WAC Building', 30, 'locked'),
(UUID(), 'WAC-202', 'WAC 202 Lecture', 'WAC Building', 50, 'locked');

-- Insert sample instructor
INSERT INTO USERS (USERID, FIRSTNAME, LASTNAME, EMAIL, USERTYPE, DEPARTMENT, EMPLOYEEID) 
VALUES (UUID(), 'John', 'Doe', 'john.doe@liceo.edu.ph', 'instructor', 'CIT Department', 'EMP002');

-- Insert sample students
INSERT INTO USERS (USERID, FIRSTNAME, LASTNAME, EMAIL, USERTYPE, DEPARTMENT, YEARLEVEL, STUDENTID) VALUES
(UUID(), 'Maria', 'Santos', 'maria.santos@liceo.edu.ph', 'student', 'CIT Department', '3', 'STU001'),
(UUID(), 'Juan', 'Cruz', 'juan.cruz@liceo.edu.ph', 'student', 'CIT Department', '3', 'STU002'),
(UUID(), 'Ana', 'Reyes', 'ana.reyes@liceo.edu.ph', 'student', 'CIT Department', '3', 'STU003');

-- Insert sample authentication methods
INSERT INTO AUTHENTICATIONMETHODS (AUTHID, USERID, METHODTYPE, IDENTIFIER, RFIDTAGNUMBER) 
SELECT UUID(), USERID, 'RFID', CONCAT('RFID_', EMPLOYEEID), CONCAT('RFID_', EMPLOYEEID)
FROM USERS WHERE USERTYPE IN ('instructor', 'admin') AND EMPLOYEEID IS NOT NULL;

INSERT INTO AUTHENTICATIONMETHODS (AUTHID, USERID, METHODTYPE, IDENTIFIER, FINGERPRINTTEMPLATE) 
SELECT UUID(), USERID, 'Fingerprint', CONCAT('FP_', STUDENTID), 'sample_fingerprint_template'
FROM USERS WHERE USERTYPE = 'student' AND STUDENTID IS NOT NULL;

-- Create indexes for better performance
CREATE INDEX idx_users_email ON USERS(EMAIL);
CREATE INDEX idx_users_type_status ON USERS(USERTYPE, STATUS);
CREATE INDEX idx_courses_instructor ON COURSES(INSTRUCTORID);
CREATE INDEX idx_courses_term ON COURSES(ACADEMICYEAR, SEMESTER);
CREATE INDEX idx_schedules_course ON CLASSSCHEDULES(COURSEID);
CREATE INDEX idx_schedules_room ON CLASSSCHEDULES(ROOMID);
CREATE INDEX idx_enrollment_user ON COURSEENROLLMENT(USERID);
CREATE INDEX idx_enrollment_course ON COURSEENROLLMENT(COURSEID);
CREATE INDEX idx_rooms_status ON ROOMS(STATUS);
CREATE INDEX idx_devices_room ON DEVICES(ROOMID);
CREATE INDEX idx_devices_type ON DEVICES(DEVICETYPE); 